N_JOGADORES = 2
N_CARTAS_INICIAL = 5
VIDA_INICIAL_JOGADORES = 100

INDICE_CARTA_POSSIVEL = ['1', '2', '3', '4', '5', '6']
COL_VALIDA = ['A', 'B', 'C', 'D', 'E']
LINHA_VALIDA = ['1', '2', '3']

NUMERO_COLUNAS = 5
NUMERO_LINHAS = 6